"""Auto-generated WebUI copy catalog for i18n key lookup."""

from __future__ import annotations

WEBUI_COPY_CATALOG: dict[str, dict[str, str]] = {
    "copy_00cb078741": {"en": "command is required for stdio mode", "zh-CN": "stdio 模式下 command 必填"},
    "copy_038db5c891": {"en": "Full channels config (supports ${ENV_VAR})", "zh-CN": "完整 channels 配置（支持 ${ENV_VAR} 占位）"},
    "copy_0487effcd2": {"en": "Unsupported media action", "zh-CN": "不支持的媒体操作"},
    "copy_04a4134683": {"en": "Exports Directory (Generated Files)", "zh-CN": "导出目录（生成文件）"},
    "copy_04aadd3a1b": {"en": "Dashboard", "zh-CN": "仪表盘"},
    "copy_050cb29a67": {"en": "Source", "zh-CN": "来源"},
    "copy_057d5e7296": {"en": "Delete endpoint", "zh-CN": "删除端点"},
    "copy_058088c938": {"en": "Channels", "zh-CN": "渠道"},
    "copy_05dcd40006": {"en": "Extra Headers JSON", "zh-CN": "附加请求头 JSON"},
    "copy_0688995328": {"en": "Unsupported channels action", "zh-CN": "不支持的渠道操作"},
    "copy_0702a848f2": {"en": "Create Endpoint", "zh-CN": "新增端点"},
    "copy_070bc42b94": {"en": "{channel}: missing `{field}`", "zh-CN": "{channel}: 缺少 `{field}`"},
    "copy_07d9decb36": {"en": "Installed MCP library entry: {name}", "zh-CN": "已安装 MCP 库条目: {name}"},
    "copy_08174841b4": {"en": "This directory stores attachments downloaded from chat channels (TG/Discord/Feishu/etc). Review before deletion.", "zh-CN": "这里是聊天渠道（TG/Discord/Feishu 等）下载的附件目录。建议先查看再删除。"},
    "copy_088192140c": {"en": "List (recommended)", "zh-CN": "列出（推荐）"},
    "copy_08adfb664f": {"en": "Select channel", "zh-CN": "选择渠道"},
    "copy_08d11b1523": {"en": "(unrestricted)", "zh-CN": "（未限制）"},
    "copy_0963abf262": {"en": "history char budget (maxHistoryChars)", "zh-CN": "history 字符预算（maxHistoryChars）"},
    "copy_0a481aedb7": {"en": "filtered", "zh-CN": "已过滤"},
    "copy_0a5b223a3d": {"en": "Add an endpoint first; this table generates quick commands after models are configured.", "zh-CN": "先新增 endpoint；配置 models 后这里会生成快捷命令。"},
    "copy_0ca5c3f138": {"en": "plain list (not recommended)", "zh-CN": "明文列表（不推荐）"},
    "copy_0cc2beb614": {"en": "These settings affect reply-language constraints and search strategy hints for new requests; no chat command needed.", "zh-CN": "这些设置会影响新请求的回复语言约束与搜索策略提示，不需要聊天命令。"},
    "copy_0fc47138dd": {"en": "fetched content does not look like SKILL.md", "zh-CN": "下载内容看起来不是 SKILL.md"},
    "copy_110d0cb33b": {"en": "Copy", "zh-CN": "复制"},
    "copy_121eedb40b": {"en": "Gateway runtime", "zh-CN": "Gateway 运行状态"},
    "copy_12300e9015": {"en": "entry_id is required", "zh-CN": "entry_id 必填"},
    "copy_134e6662db": {"en": "Name", "zh-CN": "名称"},
    "copy_13aba60c95": {"en": "Workspace", "zh-CN": "工作区"},
    "copy_13c9518932": {"en": "API Base (supports ${ENV})", "zh-CN": "API Base（可用 ${ENV} 占位）"},
    "copy_1441c40e12": {"en": "Choose one channel, edit fields below, then save.", "zh-CN": "先选择渠道，再编辑下方配置并保存。"},
    "copy_146f0323c0": {"en": "missing deps", "zh-CN": "缺少依赖"},
    "copy_15ef73070b": {"en": "overwrite", "zh-CN": "覆盖已有"},
    "copy_1618f124f1": {"en": "Media", "zh-CN": "媒体文件"},
    "copy_16376aed4e": {"en": "skill_url must return text/markdown content", "zh-CN": "skill_url 必须返回 text/markdown 内容"},
    "copy_187e101721": {"en": "skill file is too large (max 512KB)", "zh-CN": "技能文件过大（最大 512KB）"},
    "copy_19d5353478": {"en": "Directory", "zh-CN": "目录"},
    "copy_1bd2ab6876": {"en": "Unavailable skills", "zh-CN": "不可用技能"},
    "copy_1ccc016b3f": {"en": "Resource Radar", "zh-CN": "资源雷达"},
    "copy_1d3b8f9014": {"en": "background", "zh-CN": "背景上下文"},
    "copy_1e396093c7": {"en": "Env main file", "zh-CN": "Env 主文件"},
    "copy_1ed56cae30": {"en": "invalid catalog entry", "zh-CN": "目录条目无效"},
    "copy_1f74de3fbd": {"en": "session cache cap (sessionCacheMaxEntries)", "zh-CN": "会话缓存上限（sessionCacheMaxEntries）"},
    "copy_1fa01967f9": {"en": "Privacy", "zh-CN": "隐私说明"},
    "copy_1fac7f174f": {"en": "Fallback language when auto-detect fails", "zh-CN": "自动检测失败时的回退语言"},
    "copy_21e76727f7": {"en": "Default model check failed: {reason}", "zh-CN": "默认模型检测失败: {reason}"},
    "copy_233b3e21f6": {"en": "Gateway state file", "zh-CN": "Gateway 状态文件"},
    "copy_234b7f09e0": {"en": "No obvious conflict found.", "zh-CN": "未发现明显冲突。"},
    "copy_2364adaaf8": {"en": "review config migration hints and resave related page", "zh-CN": "查看配置迁移提示后到对应页面重存"},
    "copy_238ada1d30": {"en": "Skill selection saved", "zh-CN": "技能选择已保存"},
    "copy_244ab9f142": {"en": "Save Skill Selection", "zh-CN": "保存技能选择"},
    "copy_250b861b98": {"en": "Example: for a Japan topic asked in Chinese, search Japanese first and summarize in Chinese.", "zh-CN": "例如中文问日本话题时，先用日语检索，再用中文总结。"},
    "copy_25eda6d173": {"en": "Default model check", "zh-CN": "默认模型检查"},
    "copy_25f1075300": {"en": "Save Skills JSON", "zh-CN": "保存 Skills JSON"},
    "copy_25f39799e0": {"en": "allowFrom storage", "zh-CN": "allowFrom 存储方式"},
    "copy_260587bc98": {"en": "Please select at least one file to delete.", "zh-CN": "请选择要删除的文件。"},
    "copy_273b6a3401": {"en": "Skill", "zh-CN": "技能"},
    "copy_28ae9db0ec": {"en": "Save Default Model", "zh-CN": "保存默认模型"},
    "copy_295ff19f57": {"en": "chars", "zh-CN": "字符"},
    "copy_2acaa55f24": {"en": "Exports Directory", "zh-CN": "导出目录设置"},
    "copy_2d51a6305e": {"en": "Enabled", "zh-CN": "启用"},
    "copy_2d5531cf4c": {"en": "Store generated result files here (txt/docx/pdf/xlsx/etc) for unified download and cleanup.", "zh-CN": "这里建议存放机器人生成的结果文件（如 txt/docx/pdf/xlsx 等），便于统一下载和清理。"},
    "copy_2da6c2c139": {"en": "File count", "zh-CN": "文件数"},
    "copy_2dab2e7014": {"en": "skill_url must use https://", "zh-CN": "skill_url 必须使用 https://"},
    "copy_2f4569bc25": {"en": "outbound queue max size (outboundQueueMaxsize, 0=unbounded)", "zh-CN": "出站队列上限（outboundQueueMaxsize，0=无限制）"},
    "copy_2f6798b85c": {"en": "CPU load(1m)", "zh-CN": "CPU 负载(1m)"},
    "copy_2f73c57a48": {"en": ")", "zh-CN": "）"},
    "copy_2fb6e908ad": {"en": "none enabled", "zh-CN": "未启用"},
    "copy_30b055667a": {"en": "Manage Models", "zh-CN": "管理模型端点"},
    "copy_30bd9ba88a": {"en": "credential env prefix", "zh-CN": "凭据环境变量前缀"},
    "copy_315dd5eb17": {"en": "tools.filesHub.exportsDir (empty = default", "zh-CN": "tools.filesHub.exportsDir（留空=默认"},
    "copy_31e6f8e53e": {"en": "Estimation uses ~1 token per 3 chars (mixed text).", "zh-CN": "估算按约 1 token ≈ 3 chars（中英混合粗估）。"},
    "copy_32ec6718b9": {"en": "media", "zh-CN": "媒体目录"},
    "copy_34fb397424": {"en": "install or import skill", "zh-CN": "请先安装或导入技能"},
    "copy_35a8d5e0d7": {"en": "allowFrom env prefix", "zh-CN": "allowFrom 环境变量前缀"},
    "copy_365b3bfe16": {"en": "tokens", "zh-CN": "tokens"},
    "copy_3783d228f3": {"en": "Save Language/Search Policy", "zh-CN": "保存语言/搜索策略"},
    "copy_3787c1bdfe": {"en": "Apply Recommended (Exa + Docloader)", "zh-CN": "应用推荐（Exa + Docloader）"},
    "copy_393787076e": {"en": "Install From Manifest URL", "zh-CN": "从清单 URL 安装"},
    "copy_3a1c583f30": {"en": "Save action validates endpoint/model availability once before writing config.", "zh-CN": "保存时会先做一次 endpoint/model 可用性检测，再写入配置。聊天里仍可用 /model 会话级切换。"},
    "copy_3a90affba0": {"en": "File Operations Overview", "zh-CN": "文件处理总览"},
    "copy_3ab1114e1f": {"en": "gc / cache", "zh-CN": "gc / 缓存"},
    "copy_3ab3d379c3": {"en": "Channels JSON Editor", "zh-CN": "Channels JSON 编辑器"},
    "copy_3b787da60e": {"en": "Manage MCP", "zh-CN": "管理 MCP"},
    "copy_3cd83f44d0": {"en": "entry_id not found in manifest: {entry_id}", "zh-CN": "manifest 中未找到 entry_id: {entry_id}"},
    "copy_3e780cf713": {"en": "Skill enabled: {name}", "zh-CN": "技能已启用: {name}"},
    "copy_3f13616515": {"en": "Env JSON (optional)", "zh-CN": "Env JSON（可选）"},
    "copy_3f3ee01072": {"en": "Model", "zh-CN": "模型"},
    "copy_3fbe0bb79a": {"en": "skill_url host must be public", "zh-CN": "skill_url 主机必须是公网地址"},
    "copy_3fdd419032": {"en": "Delete this file?", "zh-CN": "删除该文件？"},
    "copy_413cf91123": {"en": "API Key (env placeholder recommended)", "zh-CN": "API Key（建议使用 env 占位）"},
    "copy_429a21f2a3": {"en": "Save", "zh-CN": "保存"},
    "copy_43b74d7952": {"en": "OK", "zh-CN": "通过"},
    "copy_44767eb12b": {"en": "Save Channels JSON", "zh-CN": "保存 Channels JSON"},
    "copy_44871f4550": {"en": "No named endpoint yet. Add one first.", "zh-CN": "还没有命名端点。先新增一个即可。"},
    "copy_47321931d7": {"en": "Uploaded attachments (media)", "zh-CN": "上传附件（media）"},
    "copy_485ebe513e": {"en": "Enable cross-lingual search hints (region topics prioritize local-language retrieval)", "zh-CN": "启用跨语言搜索提示（地区话题优先本地语言检索）"},
    "copy_4965b21e34": {"en": "Mode", "zh-CN": "模式"},
    "copy_4ad2d532fe": {"en": "Install Entry", "zh-CN": "安装条目"},
    "copy_4aee8ab49d": {"en": "Global skills", "zh-CN": "全局技能目录"},
    "copy_4d1a12097f": {"en": "Target (masked)", "zh-CN": "目标（脱敏）"},
    "copy_4d554a1bae": {"en": "manifest JSON must be an array", "zh-CN": "manifest JSON 必须是数组"},
    "copy_4d98d279f5": {"en": "add to enabled servers", "zh-CN": "加入启用服务列表"},
    "copy_501527958e": {"en": "Exports directory setting saved.", "zh-CN": "导出目录设置已保存。"},
    "copy_506d69257d": {"en": "Skill Library (Local)", "zh-CN": "技能库（本地）"},
    "copy_51356dc67d": {"en": "Export list", "zh-CN": "导出目录"},
    "copy_51f4629e85": {"en": "tools.enabled does not include `message`; some channel replies may fail.", "zh-CN": "tools.enabled 未包含 `message`，部分渠道回传可能异常。"},
    "copy_524d604e3e": {"en": "Channel Overview", "zh-CN": "多渠道概览"},
    "copy_53236bcf72": {"en": "Directory is empty", "zh-CN": "目录为空"},
    "copy_5411c637a0": {"en": "manifest entry missing config object", "zh-CN": "manifest 条目缺少 config 对象"},
    "copy_5568eb900a": {"en": "Use input(media) / process(workspace) / output(exports) layering to reduce accidental deletion and duplicated tools.", "zh-CN": "遵循“输入(media) / 处理(workspace) / 输出(exports)”分层，减少误删原件和工具重复。"},
    "copy_5591e4e0e7": {"en": "Default reply language (final answer)", "zh-CN": "默认回复语言（最终回复）"},
    "copy_589271255b": {"en": "Tools config saved", "zh-CN": "Tools 配置已保存"},
    "copy_597112b702": {"en": "e.g. exa", "zh-CN": "例如：exa"},
    "copy_59b62711cb": {"en": "These commands can be sent directly in chat (TG/Discord/etc.) for session-level model switching.", "zh-CN": "这些命令可直接发给机器人会话（TG/Discord/其他渠道）进行会话级模型切换。"},
    "copy_5a41b40e6c": {"en": "fix in MCP page", "zh-CN": "去 MCP 页面修复"},
    "copy_5d53cca28d": {"en": "SKILL.md URL", "zh-CN": "SKILL.md 链接"},
    "copy_5dd3b6b779": {"en": "Skill Library", "zh-CN": "技能库"},
    "copy_5ebcc6b810": {"en": "Endpoint", "zh-CN": "端点"},
    "copy_608437a7b5": {"en": "Channels Ready", "zh-CN": "渠道就绪"},
    "copy_60c72094e1": {"en": "Save Selected Channel", "zh-CN": "保存当前渠道配置"},
    "copy_61500944a3": {"en": "url is required for HTTP mode", "zh-CN": "HTTP 模式下 url 必填"},
    "copy_618ca36be5": {"en": "inline image size cap (maxInlineImageBytes)", "zh-CN": "内联图片大小上限（maxInlineImageBytes）"},
    "copy_6302492760": {"en": "none", "zh-CN": "未配置"},
    "copy_63443cb4da": {"en": "Manage Media", "zh-CN": "管理媒体文件"},
    "copy_63c7bac2c0": {"en": "Server key", "zh-CN": "服务键"},
    "copy_65c85870d1": {"en": "Route hint", "zh-CN": "路由建议"},
    "copy_6765a6dc45": {"en": "system prompt cache TTL (systemPromptCacheTtlSeconds)", "zh-CN": "系统提示缓存秒数（systemPromptCacheTtlSeconds）"},
    "copy_6abb2e76fc": {"en": "enabled", "zh-CN": "已启用"},
    "copy_6acd8d881d": {"en": "Unsupported MCP action", "zh-CN": "不支持的 MCP 操作"},
    "copy_6b5232960d": {"en": "Models (CSV; empty = unrestricted)", "zh-CN": "Models（逗号分隔；空=不限）"},
    "copy_6b52d87f4c": {"en": "env placeholders (recommended)", "zh-CN": "环境变量占位（推荐）"},
    "copy_6bbea136db": {"en": "Name (used by /model endpoint/model)", "zh-CN": "名字（用于 /model endpoint/model）"},
    "copy_6bdbf6692a": {"en": "fix in Models & APIs", "zh-CN": "去模型与接口修复"},
    "copy_6c0cb7decc": {"en": "Refreshed {scope} list.", "zh-CN": "已刷新{scope}列表。"},
    "copy_6c7768039b": {"en": "Use JSON editor below for full control of all channel fields.", "zh-CN": "下方 JSON 编辑器可覆盖全部 channel 字段。"},
    "copy_6d1d03802d": {"en": "Env directory", "zh-CN": "Env 目录"},
    "copy_6e4c0158a8": {"en": "inline image cap", "zh-CN": "内联图片上限"},
    "copy_6ef4b39e70": {"en": "Channel", "zh-CN": "渠道"},
    "copy_70a029499f": {"en": "manifest_url is required", "zh-CN": "manifest_url 必填"},
    "copy_70d9d9c07c": {"en": "e.g. uvx", "zh-CN": "例如：uvx"},
    "copy_711ea05089": {"en": "inbound queue max size (inboundQueueMaxsize, 0=unbounded)", "zh-CN": "入站队列上限（inboundQueueMaxsize，0=无限制）"},
    "copy_71ed591219": {"en": "e.g. https://example.com/mcp", "zh-CN": "例如：https://example.com/mcp"},
    "copy_722f7700c8": {"en": "{scope}: deleted {deleted}{missing_en}", "zh-CN": "{scope}已删除 {deleted} 个文件{missing_zh}"},
    "copy_729c743ff6": {"en": "Add Endpoint", "zh-CN": "新增端点"},
    "copy_74880df377": {"en": "Media Directory (Uploaded Attachments)", "zh-CN": "媒体目录（上传附件）"},
    "copy_77c9a73844": {"en": "exports", "zh-CN": "导出目录"},
    "copy_78b37de923": {"en": "Imported skill: {name}", "zh-CN": "已导入技能: {name}"},
    "copy_79251df1bb": {"en": "Add Custom MCP Server", "zh-CN": "添加自定义 MCP 服务"},
    "copy_7a13648627": {"en": "Named Endpoints", "zh-CN": "命名端点"},
    "copy_7a3c11935c": {"en": "Import Skill From URL", "zh-CN": "从 URL 导入技能"},
    "copy_7aa9acf128": {"en": "Memory used", "zh-CN": "内存占用"},
    "copy_7bd0a9f0ea": {"en": "Save MCP Server", "zh-CN": "保存 MCP 服务"},
    "copy_7e986f4983": {"en": "Page", "zh-CN": "分页"},
    "copy_7ea154897f": {"en": "Display name / filename", "zh-CN": "显示名 / 文件名"},
    "copy_7f7de13549": {"en": "invalid alias (self-mapping): {lhs} -> {rhs}", "zh-CN": "alias 无效（自映射）: {lhs} -> {rhs}"},
    "copy_80aa5bc530": {"en": "No budget pressure detected.", "zh-CN": "未检测到预算压力。"},
    "copy_8225253a3e": {"en": "memory char budget (maxMemoryContextChars)", "zh-CN": "MEMORY 字符预算（maxMemoryContextChars）"},
    "copy_837589b623": {"en": "Auto-apply is guaranteed only when WebUI and gateway share the same NANOBOT_DATA_DIR and gateway is alive.", "zh-CN": "仅当 WebUI 与 gateway 使用同一个 NANOBOT_DATA_DIR 且 gateway 在线时，才能保证自动生效。"},
    "copy_8540a2dd2f": {"en": "command", "zh-CN": "命令"},
    "copy_8660e310e0": {"en": "e.g. https://raw.githubusercontent.com/.../mcp-library.json", "zh-CN": "例如：https://raw.githubusercontent.com/.../mcp-library.json"},
    "copy_867f77e184": {"en": "Consistency Checks", "zh-CN": "一致性检查"},
    "copy_86a9787d71": {"en": "Unsupported endpoints action", "zh-CN": "不支持的端点操作"},
    "copy_8782c94f6d": {"en": "Config migration hints", "zh-CN": "配置迁移提示"},
    "copy_8820dae183": {"en": "e.g. https://raw.githubusercontent.com/.../SKILL.md", "zh-CN": "例如：https://raw.githubusercontent.com/.../SKILL.md"},
    "copy_8842cf14ea": {"en": "Missing-dependency skills can stay disabled by default.", "zh-CN": "缺少依赖的技能建议默认禁用。"},
    "copy_88a0c6254f": {"en": "Save Runtime Budget", "zh-CN": "保存资源策略"},
    "copy_89c2bfd523": {"en": "Health", "zh-CN": "健康检查"},
    "copy_8a0970d9c7": {"en": "Endpoint not found: {name}", "zh-CN": "端点不存在: {name}"},
    "copy_8a3f96ce5c": {"en": "Language & Search Policy", "zh-CN": "语言与搜索策略"},
    "copy_8ae98f1a47": {"en": "Health Score", "zh-CN": "健康分"},
    "copy_8b572bd92c": {"en": "No skill found.", "zh-CN": "未发现技能。"},
    "copy_8baf8f5ce5": {"en": "Modified", "zh-CN": "修改时间"},
    "copy_8bf66049d6": {"en": "Entry ID", "zh-CN": "条目 ID"},
    "copy_8e763e147d": {"en": "mode must be url or stdio", "zh-CN": "mode 必须是 url 或 stdio"},
    "copy_8e9b1a1c09": {"en": "Models & APIs", "zh-CN": "模型与接口"},
    "copy_8ea9ea44b7": {"en": "e.g. myserver", "zh-CN": "例如：myserver"},
    "copy_8eae048dc6": {"en": "For full diagnostics, run", "zh-CN": "更详细诊断建议使用"},
    "copy_8f44b25b19": {"en": "global copy missing", "zh-CN": "全局目录未安装"},
    "copy_91fcf79c26": {"en": "If TG filename looks random, check", "zh-CN": "如果 TG 文件名看起来像随机串，请查看"},
    "copy_938e06cb8a": {"en": "Status", "zh-CN": "状态"},
    "copy_95764a462a": {"en": "per-turn timeout in seconds (turnTimeoutSeconds)", "zh-CN": "单轮超时秒数（turnTimeoutSeconds）"},
    "copy_96da16a746": {"en": "Requires", "zh-CN": "依赖"},
    "copy_97cdecae41": {"en": "new uploads try to keep original filename/extension", "zh-CN": "新上传文件会尽量保留原文件名/后缀"},
    "copy_98801c7c59": {"en": "Type (protocol/router)", "zh-CN": "类型（协议/路由）"},
    "copy_98a1f7d64b": {"en": "background char budget (maxBackgroundContextChars)", "zh-CN": "背景字符预算（maxBackgroundContextChars）"},
    "copy_9950f43b0f": {"en": "Do not place raw API keys directly in JSON where possible.", "zh-CN": "建议不要在 JSON 里直接写明文 API Key。"},
    "copy_998e78e6e0": {"en": "Delete selected", "zh-CN": "删除选中项"},
    "copy_9d0b57f659": {"en": "This is a lightweight runtime snapshot from the current host.", "zh-CN": "这是当前主机的轻量运行快照。"},
    "copy_9f5d6873cf": {"en": "Based on model/channels/MCP runtime checks", "zh-CN": "基于模型/渠道/MCP 运行时检查"},
    "copy_9fd2cc0774": {"en": "custom endpoint/model (optional)", "zh-CN": "自定义 endpoint/model（可选）"},
    "copy_a0f9eb524c": {"en": "e.g. my-skill", "zh-CN": "例如：my-skill"},
    "copy_a10261167f": {"en": "server_name is required", "zh-CN": "server_name 必填"},
    "copy_a14761702c": {"en": "allowFrom supports both plain IDs and env placeholders; team sharing usually prefers env placeholders.", "zh-CN": "allowFrom 同时支持明文和环境变量占位；团队共享配置通常建议用 env 占位。"},
    "copy_a161398273": {"en": "skill_name is required", "zh-CN": "skill_name 必填"},
    "copy_a26ad10e17": {"en": "Save exports directory", "zh-CN": "保存导出目录"},
    "copy_a31ec3dd8b": {"en": "Global Channel Behavior", "zh-CN": "通道行为（全局）"},
    "copy_a571185758": {"en": "Server Key", "zh-CN": "服务键"},
    "copy_aa5f0c6d2a": {"en": "No MCP server configured.", "zh-CN": "尚未配置 MCP 服务。"},
    "copy_aa8fa4d0f7": {"en": "e.g. package@latest, --flag", "zh-CN": "例如：package@latest, --flag"},
    "copy_ac28a9ca4e": {"en": "Skills JSON (Advanced)", "zh-CN": "Skills JSON（高级）"},
    "copy_ac33b7783e": {"en": "ensure gateway uses same NANOBOT_DATA_DIR and is running", "zh-CN": "确保 gateway 使用相同 NANOBOT_DATA_DIR 并处于运行中"},
    "copy_ac7cdf0e5b": {"en": "Manifest format: [{id,name,server_name,config:{url|command,args,env}}]", "zh-CN": "清单格式：[{id,name,server_name,config:{url|command,args,env}}]"},
    "copy_ac8ae900ca": {"en": "Multi-channel Quick Setup (Generic)", "zh-CN": "多渠道通用快速配置"},
    "copy_ad1ffbb413": {"en": "install missing dependencies", "zh-CN": "请安装缺失依赖"},
    "copy_ad3b97116f": {"en": "HTTP URL", "zh-CN": "HTTP 地址"},
    "copy_adb4fa9484": {"en": "Endpoint name cannot be empty.", "zh-CN": "端点名称不能为空。"},
    "copy_aed9d3ab61": {"en": "Actionable Checks", "zh-CN": "待处理检查项"},
    "copy_aef26c2ad9": {"en": "Enable this endpoint", "zh-CN": "启用该端点"},
    "copy_b1719a8f3f": {"en": "MCP", "zh-CN": "MCP"},
    "copy_b1be526ebb": {"en": "Unsupported skills action", "zh-CN": "不支持的技能操作"},
    "copy_b1d5dd1a0c": {"en": "Action", "zh-CN": "操作"},
    "copy_b2aefaa537": {"en": "MCP servers", "zh-CN": "MCP 服务数"},
    "copy_b2f086be87": {"en": "{channel}: missing env `{name}`", "zh-CN": "{channel}: 缺少环境变量 `{name}`"},
    "copy_b334dbf724": {"en": "tune budgets", "zh-CN": "调整预算"},
    "copy_b4fa9a05e7": {"en": "This page masks sensitive query values in MCP URLs.", "zh-CN": "本页会自动脱敏 MCP URL 中的敏感参数。"},
    "copy_b554959adb": {"en": "credential storage", "zh-CN": "凭据存储方式"},
    "copy_b69f65c3f3": {"en": "tools.enabled does not include `spawn`; background sub-agent capability is disabled.", "zh-CN": "tools.enabled 未包含 `spawn`，后台子代理能力不可用。"},
    "copy_b8be6984d7": {"en": "Export files", "zh-CN": "导出文件数"},
    "copy_b91f0534e2": {"en": "Skill Notes", "zh-CN": "技能说明"},
    "copy_b9456b69aa": {"en": "Import", "zh-CN": "导入"},
    "copy_b948ecad01": {"en": "recommended off", "zh-CN": "建议关闭"},
    "copy_b95244aab5": {"en": "Config snippet (masked)", "zh-CN": "配置片段（脱敏）"},
    "copy_bb68b83d71": {"en": "available", "zh-CN": "可用"},
    "copy_bc76551059": {"en": "missing env: {hint}", "zh-CN": "缺少环境变量: {hint}"},
    "copy_bdd6a4e999": {"en": "API Base", "zh-CN": "API 地址"},
    "copy_bdeb1df337": {"en": "Saved MCP server: {server_name}", "zh-CN": "MCP 服务已保存: {server_name}"},
    "copy_be783d3e39": {"en": "overwrite existing server", "zh-CN": "覆盖已有同名服务"},
    "copy_bf187784b8": {"en": "Command (for stdio mode)", "zh-CN": "命令（stdio 模式）"},
    "copy_c13efabddc": {"en": "GC interval in turns (gcEveryTurns, 0=off)", "zh-CN": "GC 间隔轮次（gcEveryTurns，0=关闭）"},
    "copy_c2a837c0d5": {"en": "Config", "zh-CN": "配置文件"},
    "copy_c31baf890e": {"en": "Delete selected files?", "zh-CN": "删除选中文件？"},
    "copy_c5accebd52": {"en": "Use the URL import box below if you want to add third-party skills.", "zh-CN": "需要三方技能时，可使用下方 URL 导入。"},
    "copy_c7252673a1": {"en": "plain text (not recommended)", "zh-CN": "明文（不推荐）"},
    "copy_c755ff960d": {"en": "allowlisted", "zh-CN": "白名单启用"},
    "copy_c766efebde": {"en": "Stdio command", "zh-CN": "标准输入输出命令"},
    "copy_c7af768dfc": {"en": "manifest entry missing server_name", "zh-CN": "manifest 条目缺少 server_name"},
    "copy_c80805754d": {"en": "Budget alerts", "zh-CN": "预算告警"},
    "copy_ca3ec87f06": {"en": "MCP Library", "zh-CN": "MCP 库"},
    "copy_cae4ed6e49": {"en": "missing command: {hint}", "zh-CN": "缺少命令: {hint}"},
    "copy_cb8da62408": {"en": "failed to fetch skill URL: {error}", "zh-CN": "拉取 skill URL 失败: {error}"},
    "copy_cc9754586e": {"en": "API Key", "zh-CN": "API 密钥"},
    "copy_cdab38948a": {"en": "Delete", "zh-CN": "删除"},
    "copy_ce386bcea5": {"en": "skill_url must include host", "zh-CN": "skill_url 必须包含主机名"},
    "copy_cf20d86a6c": {"en": "invalid alias: {lhs} -> {rhs}", "zh-CN": "alias 无效: {lhs} -> {rhs}"},
    "copy_cf3f4b45e3": {"en": "Type", "zh-CN": "类型"},
    "copy_cf94509574": {"en": "Prefer", "zh-CN": "建议使用"},
    "copy_d0a0e99437": {"en": "Skill name", "zh-CN": "技能名"},
    "copy_d0dcd15837": {"en": "Skills config saved", "zh-CN": "Skills 配置已保存"},
    "copy_d1a3716b38": {"en": "Default Model", "zh-CN": "默认模型"},
    "copy_d23e378056": {"en": "Please select a valid channel.", "zh-CN": "请选择一个有效渠道。"},
    "copy_d2e63e8b45": {"en": "web_search provider is enabled, but web_search is not in tools.enabled.", "zh-CN": "web_search provider 已启用，但 web_search 不在 tools.enabled。"},
    "copy_d58fe3eff7": {"en": "MCP Servers", "zh-CN": "MCP 服务"},
    "copy_d731db428a": {"en": "Skills", "zh-CN": "技能"},
    "copy_d7a63bbf89": {"en": "for unified management", "zh-CN": "统一管理"},
    "copy_d846d56e2c": {"en": "Token Budget Radar", "zh-CN": "Token 预算雷达"},
    "copy_d87e01ad93": {"en": "Media files", "zh-CN": "媒体文件数"},
    "copy_d98c0f9a65": {"en": "enable in skill selection", "zh-CN": "可在技能选择里启用"},
    "copy_d99390fcdd": {"en": "In-chat quick switch commands", "zh-CN": "聊天内快捷切换命令"},
    "copy_d9e9a841af": {"en": "history", "zh-CN": "历史上下文"},
    "copy_da94efacfc": {"en": "requires: {hint}", "zh-CN": "依赖: {hint}"},
    "copy_dc4ca1d540": {"en": "Args (CSV, stdio mode)", "zh-CN": "参数（CSV，stdio 模式）"},
    "copy_dd00e74022": {"en": "In-chat File Commands (Recommended)", "zh-CN": "聊天内文件管理命令（推荐）"},
    "copy_ddc9843ac5": {"en": "Manage Channels", "zh-CN": "管理聊天渠道"},
    "copy_e05e1dba4e": {"en": "Size", "zh-CN": "大小"},
    "copy_e0f2204417": {"en": "Installed MCP from manifest: {server_name}", "zh-CN": "已从 manifest 安装 MCP: {server_name}"},
    "copy_e117e3ade1": {"en": "web_search is set to exa_mcp, but exa MCP server is not configured.", "zh-CN": "web_search 使用 exa_mcp，但未配置 exa MCP server。"},
    "copy_e1c753b2f4": {"en": "Install", "zh-CN": "安装"},
    "copy_e1e78e6048": {"en": "Runtime Paths & Counters", "zh-CN": "运行目录与计数"},
    "copy_e22992ebe6": {"en": "Gateway auto-reload", "zh-CN": "Gateway 自动热重载"},
    "copy_e2d32cb2de": {"en": "FAIL", "zh-CN": "失败"},
    "copy_e49ca5cd39": {"en": "Keep only skills you actually use to reduce startup checks and noise.", "zh-CN": "只保留常用技能，可减少启动检查和日志噪音。"},
    "copy_e539e84dae": {"en": "Auto-compact background (structured first, truncate later)", "zh-CN": "自动压缩背景信息（优先结构化压缩，再截断）"},
    "copy_e53da62285": {"en": "Disk used(/)", "zh-CN": "磁盘占用(/)"},
    "copy_e573c984a6": {"en": "open endpoint and resave models", "zh-CN": "打开端点后重新保存 models"},
    "copy_e6e3e5859b": {"en": "Recommended MCP defaults applied (Exa + Docloader).", "zh-CN": "推荐 MCP 默认配置已应用（Exa + Docloader）。"},
    "copy_e721609807": {"en": "Unknown MCP library entry: {library_id}", "zh-CN": "未知 MCP 库条目: {library_id}"},
    "copy_e77abf6493": {"en": "For TG-heavy usage, keep", "zh-CN": "主用 TG 时建议保持"},
    "copy_e8f442342e": {"en": "Install to Global", "zh-CN": "安装到全局"},
    "copy_e92d513a99": {"en": "Manifest URL (raw JSON list)", "zh-CN": "清单 URL（raw JSON 列表）"},
    "copy_ea3a2a448d": {"en": "Enable", "zh-CN": "启用"},
    "copy_ea790065d7": {"en": "Adjust in small steps and observe response quality/resource usage before tightening further.", "zh-CN": "建议先小步调整并观察响应质量与资源占用，再继续收紧预算。"},
    "copy_ea85f2b46c": {"en": "No blocking issue found.", "zh-CN": "未发现阻塞问题。"},
    "copy_eb0935dd77": {"en": "total context cap", "zh-CN": "总上下文预算"},
    "copy_eb1e822ae6": {"en": "Description", "zh-CN": "说明"},
    "copy_ebb7c85be7": {"en": "default_model cannot be empty.", "zh-CN": "default_model 不能为空。"},
    "copy_ededde3efe": {"en": "Server", "zh-CN": "服务"},
    "copy_ee97554ed4": {"en": "Models (CSV)", "zh-CN": "Models（逗号分隔）"},
    "copy_f234913c4f": {"en": "Unknown skill library entry: {entry_id}", "zh-CN": "未知技能库条目: {entry_id}"},
    "copy_f433503b85": {"en": "Path", "zh-CN": "路径"},
    "copy_f5e7ed533c": {"en": "Name", "zh-CN": "名字"},
    "copy_f6287abbe3": {"en": "allowFrom list (CSV)", "zh-CN": "allowFrom 列表（逗号分隔）"},
    "copy_f6639efa56": {"en": "id1, id2", "zh-CN": "用户ID1, 用户ID2"},
    "copy_f74fcb1799": {"en": "Runtime & Context Budgets", "zh-CN": "资源与上下文预算"},
    "copy_f89676fdd4": {"en": "Generated outputs (exports)", "zh-CN": "生成输出（exports）"},
    "copy_f897aa302e": {"en": "MCP server '{name}' already exists. Enable overwrite to replace.", "zh-CN": "MCP 服务 '{name}' 已存在。勾选覆盖后可替换。"},
    "copy_f8edffc1b1": {"en": "fix in Channels page", "zh-CN": "去渠道页面修复"},
    "copy_f99c379bf8": {"en": "Missing endpoint name.", "zh-CN": "缺少端点名称。"},
    "copy_faecc2d2df": {"en": "Example: /data/nanobot-exports or exports", "zh-CN": "例如：/data/nanobot-exports 或 exports"},
    "copy_fc1314b439": {"en": "Reset to default", "zh-CN": "恢复默认目录"},
    "copy_fc94e4673d": {"en": "memory", "zh-CN": "记忆上下文"},
    "copy_fd1d8f61cd": {"en": "URL (for HTTP mode)", "zh-CN": "URL（HTTP 模式）"},
}
