#!/usr/bin/env python3
"""Clean local runtime caches generated by tests/lint runs."""

from __future__ import annotations

import shutil
from pathlib import Path


def _safe_rmtree(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path, ignore_errors=True)


def main() -> int:
    repo_root = Path(__file__).resolve().parents[2]

    # Tool caches at repo root.
    _safe_rmtree(repo_root / ".pytest_cache")
    _safe_rmtree(repo_root / ".ruff_cache")

    # Python bytecode caches.
    for pycache_dir in repo_root.rglob("__pycache__"):
        _safe_rmtree(pycache_dir)

    print("[cleanup-runtime-cache] removed .pytest_cache/.ruff_cache/__pycache__")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
