"""Auto-generated WebUI copy catalog for i18n key lookup."""

from __future__ import annotations

WEBUI_COPY_CATALOG: dict[str, dict[str, str]] = {
    "copy_00cb078741": {"en": 'command is required for stdio mode', "zh-CN": 'stdio 模式下 command 必填'},
    "copy_038db5c891": {"en": 'Full channels config (supports ${ENV_VAR})', "zh-CN": '完整 channels 配置（支持 ${ENV_VAR} 占位）'},
    "copy_03acb01292": {"en": 'Risk Items', "zh-CN": '风险项'},
    "copy_04a4134683": {"en": 'Exports Directory (Generated Files)', "zh-CN": '导出目录（生成文件）'},
    "copy_04aadd3a1b": {"en": 'Dashboard', "zh-CN": '仪表盘'},
    "copy_050cb29a67": {"en": 'Source', "zh-CN": '来源'},
    "copy_057d5e7296": {"en": 'Delete endpoint', "zh-CN": '删除端点'},
    "copy_058088c938": {"en": 'Channels', "zh-CN": '渠道'},
    "copy_05dcd40006": {"en": 'Extra Headers JSON', "zh-CN": '附加请求头 JSON'},
    "copy_0688995328": {"en": 'Unsupported channels action', "zh-CN": '不支持的渠道操作'},
    "copy_0702a848f2": {"en": 'Create Endpoint', "zh-CN": '新增端点'},
    "copy_070bc42b94": {"en": '{channel}: missing `{field}`', "zh-CN": '{channel}: 缺少 `{field}`'},
    "copy_07d9decb36": {"en": 'Installed MCP library entry: {name}', "zh-CN": '已安装 MCP 库条目: {name}'},
    "copy_08adfb664f": {"en": 'Select channel', "zh-CN": '选择渠道'},
    "copy_08d11b1523": {"en": '(unrestricted)', "zh-CN": '（未限制）'},
    "copy_0963abf262": {"en": 'history char budget (maxHistoryChars)', "zh-CN": 'history 字符预算（maxHistoryChars）'},
    "copy_0a5b223a3d": {"en": 'Add an endpoint first; this table generates quick commands after models are configured.', "zh-CN": '先新增 endpoint；配置 models 后这里会生成快捷命令。'},
    "copy_0b539397d6": {"en": 'Memory', "zh-CN": '内存'},
    "copy_0ca5c3f138": {"en": 'plain list (not recommended)', "zh-CN": '明文列表（不推荐）'},
    "copy_0fc47138dd": {"en": 'fetched content does not look like SKILL.md', "zh-CN": '下载内容看起来不是 SKILL.md'},
    "copy_110d0cb33b": {"en": 'Copy', "zh-CN": '复制'},
    "copy_121eedb40b": {"en": 'Gateway runtime', "zh-CN": 'Gateway 运行状态'},
    "copy_12300e9015": {"en": 'entry_id is required', "zh-CN": 'entry_id 必填'},
    "copy_134e6662db": {"en": 'Name', "zh-CN": '名称'},
    "copy_13aba60c95": {"en": 'Workspace', "zh-CN": '工作区'},
    "copy_13c9518932": {"en": 'API Base (supports ${ENV})', "zh-CN": 'API Base（可用 ${ENV} 占位）'},
    "copy_146f0323c0": {"en": 'missing deps', "zh-CN": '缺少依赖'},
    "copy_15d44f9bd5": {"en": 'Runtime Checks', "zh-CN": '运行检查'},
    "copy_15ef73070b": {"en": 'overwrite', "zh-CN": '覆盖已有'},
    "copy_1618f124f1": {"en": 'Media', "zh-CN": '媒体文件'},
    "copy_16376aed4e": {"en": 'skill_url must return text/markdown content', "zh-CN": 'skill_url 必须返回 text/markdown 内容'},
    "copy_187e101721": {"en": 'skill file is too large (max 512KB)', "zh-CN": '技能文件过大（最大 512KB）'},
    "copy_19d5353478": {"en": 'Directory', "zh-CN": '目录'},
    "copy_1d3b8f9014": {"en": 'background', "zh-CN": '背景上下文'},
    "copy_1e396093c7": {"en": 'Env main file', "zh-CN": 'Env 主文件'},
    "copy_1ed56cae30": {"en": 'invalid catalog entry', "zh-CN": '目录条目无效'},
    "copy_1f74de3fbd": {"en": 'session cache cap (sessionCacheMaxEntries)', "zh-CN": '会话缓存上限（sessionCacheMaxEntries）'},
    "copy_1fac7f174f": {"en": 'Fallback language when auto-detect fails', "zh-CN": '自动检测失败时的回退语言'},
    "copy_21e76727f7": {"en": 'Default model check failed: {reason}', "zh-CN": '默认模型检测失败: {reason}'},
    "copy_233b3e21f6": {"en": 'Gateway state file', "zh-CN": 'Gateway 状态文件'},
    "copy_234b7f09e0": {"en": 'No obvious conflict found.', "zh-CN": '未发现明显冲突。'},
    "copy_2364adaaf8": {"en": 'review config migration hints and resave related page', "zh-CN": '查看配置迁移提示后到对应页面重存'},
    "copy_238ada1d30": {"en": 'Skill selection saved', "zh-CN": '技能选择已保存'},
    "copy_244ab9f142": {"en": 'Save Skill Selection', "zh-CN": '保存技能选择'},
    "copy_25eda6d173": {"en": 'Default model check', "zh-CN": '默认模型检查'},
    "copy_25f1075300": {"en": 'Save Skills JSON', "zh-CN": '保存 Skills JSON'},
    "copy_25f39799e0": {"en": 'allowFrom storage', "zh-CN": 'allowFrom 存储方式'},
    "copy_273b6a3401": {"en": 'Skill', "zh-CN": '技能'},
    "copy_2785720d16": {"en": 'paused', "zh-CN": '已暂停'},
    "copy_28ae9db0ec": {"en": 'Save Default Model', "zh-CN": '保存默认模型'},
    "copy_295ff19f57": {"en": 'chars', "zh-CN": '字符'},
    "copy_2acaa55f24": {"en": 'Exports Directory', "zh-CN": '导出目录设置'},
    "copy_2d51a6305e": {"en": 'Enabled', "zh-CN": '启用'},
    "copy_2da6c2c139": {"en": 'File count', "zh-CN": '文件数'},
    "copy_2dab2e7014": {"en": 'skill_url must use https://', "zh-CN": 'skill_url 必须使用 https://'},
    "copy_2f4569bc25": {"en": 'outbound queue max size (outboundQueueMaxsize, 0=unbounded)', "zh-CN": '出站队列上限（outboundQueueMaxsize，0=无限制）'},
    "copy_2f6798b85c": {"en": 'CPU load(1m)', "zh-CN": 'CPU 负载(1m)'},
    "copy_2f73c57a48": {"en": ')', "zh-CN": '）'},
    "copy_30b055667a": {"en": 'Manage Models', "zh-CN": '管理模型端点'},
    "copy_30bd9ba88a": {"en": 'credential env prefix', "zh-CN": '凭据环境变量前缀'},
    "copy_314d11eaa0": {"en": 'Composite score from channels/model/MCP/budget checks', "zh-CN": '基于渠道/模型/MCP/预算检查综合得分'},
    "copy_315dd5eb17": {"en": 'tools.filesHub.exportsDir (empty = default', "zh-CN": 'tools.filesHub.exportsDir（留空=默认'},
    "copy_34fb397424": {"en": 'install or import skill', "zh-CN": '请先安装或导入技能'},
    "copy_35a8d5e0d7": {"en": 'allowFrom env prefix', "zh-CN": 'allowFrom 环境变量前缀'},
    "copy_365b3bfe16": {"en": 'tokens', "zh-CN": 'tokens'},
    "copy_3783d228f3": {"en": 'Save Language/Search Policy', "zh-CN": '保存语言/搜索策略'},
    "copy_393787076e": {"en": 'Install From Manifest URL', "zh-CN": '从清单 URL 安装'},
    "copy_3a90affba0": {"en": 'File Operations Overview', "zh-CN": '文件处理总览'},
    "copy_3ab1114e1f": {"en": 'gc / cache', "zh-CN": 'gc / 缓存'},
    "copy_3ab3d379c3": {"en": 'Channels JSON Editor', "zh-CN": 'Channels JSON 编辑器'},
    "copy_3b787da60e": {"en": 'Manage MCP', "zh-CN": '管理 MCP'},
    "copy_3cd83f44d0": {"en": 'entry_id not found in manifest: {entry_id}', "zh-CN": 'manifest 中未找到 entry_id: {entry_id}'},
    "copy_3e780cf713": {"en": 'Skill enabled: {name}', "zh-CN": '技能已启用: {name}'},
    "copy_3f13616515": {"en": 'Env JSON (optional)', "zh-CN": 'Env JSON（可选）'},
    "copy_3f3ee01072": {"en": 'Model', "zh-CN": '模型'},
    "copy_3fbe0bb79a": {"en": 'skill_url host must be public', "zh-CN": 'skill_url 主机必须是公网地址'},
    "copy_3fdd419032": {"en": 'Delete this file?', "zh-CN": '删除该文件？'},
    "copy_413cf91123": {"en": 'API Key (env placeholder recommended)', "zh-CN": 'API Key（建议使用 env 占位）'},
    "copy_429a21f2a3": {"en": 'Save', "zh-CN": '保存'},
    "copy_43b74d7952": {"en": 'OK', "zh-CN": '通过'},
    "copy_44767eb12b": {"en": 'Save Channels JSON', "zh-CN": '保存 Channels JSON'},
    "copy_44871f4550": {"en": 'No named endpoint yet. Add one first.', "zh-CN": '还没有命名端点。先新增一个即可。'},
    "copy_485ebe513e": {"en": 'Enable cross-lingual search hints (region topics prioritize local-language retrieval)', "zh-CN": '启用跨语言搜索提示（地区话题优先本地语言检索）'},
    "copy_4965b21e34": {"en": 'Mode', "zh-CN": '模式'},
    "copy_4ad2d532fe": {"en": 'Install Entry', "zh-CN": '安装条目'},
    "copy_4aee8ab49d": {"en": 'Global skills', "zh-CN": '全局技能目录'},
    "copy_4d1a12097f": {"en": 'Target (masked)', "zh-CN": '目标（脱敏）'},
    "copy_4d554a1bae": {"en": 'manifest JSON must be an array', "zh-CN": 'manifest JSON 必须是数组'},
    "copy_4d98d279f5": {"en": 'add to enabled servers', "zh-CN": '加入启用服务列表'},
    "copy_506d69257d": {"en": 'Skill Library (Local)', "zh-CN": '技能库（本地）'},
    "copy_51f4629e85": {"en": 'tools.enabled does not include `message`; some channel replies may fail.', "zh-CN": 'tools.enabled 未包含 `message`，部分渠道回传可能异常。'},
    "copy_524d604e3e": {"en": 'Channel Overview', "zh-CN": '多渠道概览'},
    "copy_52b07c11bb": {"en": 'MCP server enabled: {server_name}', "zh-CN": 'MCP 服务已启用: {server_name}'},
    "copy_53236bcf72": {"en": 'Directory is empty', "zh-CN": '目录为空'},
    "copy_5411c637a0": {"en": 'manifest entry missing config object', "zh-CN": 'manifest 条目缺少 config 对象'},
    "copy_5591e4e0e7": {"en": 'Default reply language (final answer)', "zh-CN": '默认回复语言（最终回复）'},
    "copy_589271255b": {"en": 'Tools config saved', "zh-CN": 'Tools 配置已保存'},
    "copy_597112b702": {"en": 'e.g. exa', "zh-CN": '例如：exa'},
    "copy_5a41b40e6c": {"en": 'fix in MCP page', "zh-CN": '去 MCP 页面修复'},
    "copy_5d53cca28d": {"en": 'SKILL.md URL', "zh-CN": 'SKILL.md 链接'},
    "copy_5dd3b6b779": {"en": 'Skill Library', "zh-CN": '技能库'},
    "copy_5ebcc6b810": {"en": 'Endpoint', "zh-CN": '端点'},
    "copy_608437a7b5": {"en": 'Channels Ready', "zh-CN": '渠道就绪'},
    "copy_60c72094e1": {"en": 'Save Selected Channel', "zh-CN": '保存当前渠道配置'},
    "copy_61500944a3": {"en": 'url is required for HTTP mode', "zh-CN": 'HTTP 模式下 url 必填'},
    "copy_618ca36be5": {"en": 'inline image size cap (maxInlineImageBytes)', "zh-CN": '内联图片大小上限（maxInlineImageBytes）'},
    "copy_63443cb4da": {"en": 'Manage Media', "zh-CN": '管理媒体文件'},
    "copy_63c7bac2c0": {"en": 'Server key', "zh-CN": '服务键'},
    "copy_6765a6dc45": {"en": 'system prompt cache TTL (systemPromptCacheTtlSeconds)', "zh-CN": '系统提示缓存秒数（systemPromptCacheTtlSeconds）'},
    "copy_6abb2e76fc": {"en": 'enabled', "zh-CN": '已启用'},
    "copy_6acd8d881d": {"en": 'Unsupported MCP action', "zh-CN": '不支持的 MCP 操作'},
    "copy_6b5232960d": {"en": 'Models (CSV; empty = unrestricted)', "zh-CN": 'Models（逗号分隔；空=不限）'},
    "copy_6b52d87f4c": {"en": 'env placeholders (recommended)', "zh-CN": '环境变量占位（推荐）'},
    "copy_6bbea136db": {"en": 'Name (used by /model endpoint/model)', "zh-CN": '名字（用于 /model endpoint/model）'},
    "copy_6bdbf6692a": {"en": 'fix in Models & APIs', "zh-CN": '去模型与接口修复'},
    "copy_6d1d03802d": {"en": 'Env directory', "zh-CN": 'Env 目录'},
    "copy_6e4c0158a8": {"en": 'inline image cap', "zh-CN": '内联图片上限'},
    "copy_6ef4b39e70": {"en": 'Channel', "zh-CN": '渠道'},
    "copy_70a029499f": {"en": 'manifest_url is required', "zh-CN": 'manifest_url 必填'},
    "copy_70d9d9c07c": {"en": 'e.g. uvx', "zh-CN": '例如：uvx'},
    "copy_711ea05089": {"en": 'inbound queue max size (inboundQueueMaxsize, 0=unbounded)', "zh-CN": '入站队列上限（inboundQueueMaxsize，0=无限制）'},
    "copy_71ed591219": {"en": 'e.g. https://example.com/mcp', "zh-CN": '例如：https://example.com/mcp'},
    "copy_729c743ff6": {"en": 'Add Endpoint', "zh-CN": '新增端点'},
    "copy_74880df377": {"en": 'Media Directory (Uploaded Attachments)', "zh-CN": '媒体目录（上传附件）'},
    "copy_76dd2ec776": {"en": 'CPU load ratio', "zh-CN": 'CPU 负载比例'},
    "copy_78b37de923": {"en": 'Imported skill: {name}', "zh-CN": '已导入技能: {name}'},
    "copy_79251df1bb": {"en": 'Add Custom MCP Server', "zh-CN": '添加自定义 MCP 服务'},
    "copy_7a13648627": {"en": 'Named Endpoints', "zh-CN": '命名端点'},
    "copy_7a3c11935c": {"en": 'Import Skill From URL', "zh-CN": '从 URL 导入技能'},
    "copy_7aa9acf128": {"en": 'Memory used', "zh-CN": '内存占用'},
    "copy_7b3007a3c6": {"en": 'no metric yet', "zh-CN": '暂无指标数据'},
    "copy_7bd0a9f0ea": {"en": 'Save MCP Server', "zh-CN": '保存 MCP 服务'},
    "copy_7e986f4983": {"en": 'Page', "zh-CN": '分页'},
    "copy_7ea154897f": {"en": 'Display name / filename', "zh-CN": '显示名 / 文件名'},
    "copy_7f7de13549": {"en": 'invalid alias (self-mapping): {lhs} -> {rhs}', "zh-CN": 'alias 无效（自映射）: {lhs} -> {rhs}'},
    "copy_80aa5bc530": {"en": 'No budget pressure detected.', "zh-CN": '未检测到预算压力。'},
    "copy_8225253a3e": {"en": 'memory char budget (maxMemoryContextChars)', "zh-CN": 'MEMORY 字符预算（maxMemoryContextChars）'},
    "copy_8540a2dd2f": {"en": 'command', "zh-CN": '命令'},
    "copy_8660e310e0": {"en": 'e.g. https://raw.githubusercontent.com/.../mcp-library.json', "zh-CN": '例如：https://raw.githubusercontent.com/.../mcp-library.json'},
    "copy_867f77e184": {"en": 'Consistency Checks', "zh-CN": '一致性检查'},
    "copy_86a9787d71": {"en": 'Unsupported endpoints action', "zh-CN": '不支持的端点操作'},
    "copy_8782c94f6d": {"en": 'Config migration hints', "zh-CN": '配置迁移提示'},
    "copy_8820dae183": {"en": 'e.g. https://raw.githubusercontent.com/.../SKILL.md', "zh-CN": '例如：https://raw.githubusercontent.com/.../SKILL.md'},
    "copy_88a0c6254f": {"en": 'Save Runtime Budget', "zh-CN": '保存资源策略'},
    "copy_89c2bfd523": {"en": 'Health', "zh-CN": '健康检查'},
    "copy_8a0970d9c7": {"en": 'Endpoint not found: {name}', "zh-CN": '端点不存在: {name}'},
    "copy_8a359853ca": {"en": 'System Health', "zh-CN": '系统健康'},
    "copy_8a3f96ce5c": {"en": 'Language & Search Policy', "zh-CN": '语言与搜索策略'},
    "copy_8b572bd92c": {"en": 'No skill found.', "zh-CN": '未发现技能。'},
    "copy_8baf8f5ce5": {"en": 'Modified', "zh-CN": '修改时间'},
    "copy_8bf66049d6": {"en": 'Entry ID', "zh-CN": '条目 ID'},
    "copy_8e763e147d": {"en": 'mode must be url or stdio', "zh-CN": 'mode 必须是 url 或 stdio'},
    "copy_8e9b1a1c09": {"en": 'Models & APIs', "zh-CN": '模型与接口'},
    "copy_8ea9ea44b7": {"en": 'e.g. myserver', "zh-CN": '例如：myserver'},
    "copy_8f44b25b19": {"en": 'global copy missing', "zh-CN": '全局目录未安装'},
    "copy_927b5a05b2": {"en": 'Skill paused: {name}', "zh-CN": '技能已暂停: {name}'},
    "copy_938e06cb8a": {"en": 'Status', "zh-CN": '状态'},
    "copy_95764a462a": {"en": 'per-turn timeout in seconds (turnTimeoutSeconds)', "zh-CN": '单轮超时秒数（turnTimeoutSeconds）'},
    "copy_96da16a746": {"en": 'Requires', "zh-CN": '依赖'},
    "copy_98801c7c59": {"en": 'Type (protocol/router)', "zh-CN": '类型（协议/路由）'},
    "copy_98a1f7d64b": {"en": 'background char budget (maxBackgroundContextChars)', "zh-CN": '背景字符预算（maxBackgroundContextChars）'},
    "copy_9fd2cc0774": {"en": 'custom endpoint/model (optional)', "zh-CN": '自定义 endpoint/model（可选）'},
    "copy_a0f9eb524c": {"en": 'e.g. my-skill', "zh-CN": '例如：my-skill'},
    "copy_a10261167f": {"en": 'server_name is required', "zh-CN": 'server_name 必填'},
    "copy_a161398273": {"en": 'skill_name is required', "zh-CN": 'skill_name 必填'},
    "copy_a26ad10e17": {"en": 'Save exports directory', "zh-CN": '保存导出目录'},
    "copy_a31ec3dd8b": {"en": 'Global Channel Behavior', "zh-CN": '通道行为（全局）'},
    "copy_a571185758": {"en": 'Server Key', "zh-CN": '服务键'},
    "copy_a94f03e889": {"en": 'ensure gateway uses same LUNAECLAW_DATA_DIR and is running', "zh-CN": '确保 gateway 使用相同 LUNAECLAW_DATA_DIR 并处于运行中'},
    "copy_aa5f0c6d2a": {"en": 'No MCP server configured.', "zh-CN": '尚未配置 MCP 服务。'},
    "copy_aa8fa4d0f7": {"en": 'e.g. package@latest, --flag', "zh-CN": '例如：package@latest, --flag'},
    "copy_ac28a9ca4e": {"en": 'Skills JSON (Advanced)', "zh-CN": 'Skills JSON（高级）'},
    "copy_ac8ae900ca": {"en": 'Multi-channel Quick Setup (Generic)', "zh-CN": '多渠道通用快速配置'},
    "copy_ad1ffbb413": {"en": 'install missing dependencies', "zh-CN": '请安装缺失依赖'},
    "copy_ad3b97116f": {"en": 'HTTP URL', "zh-CN": 'HTTP 地址'},
    "copy_adb4fa9484": {"en": 'Endpoint name cannot be empty.', "zh-CN": '端点名称不能为空。'},
    "copy_aed9d3ab61": {"en": 'Actionable Checks', "zh-CN": '待处理检查项'},
    "copy_aef26c2ad9": {"en": 'Enable this endpoint', "zh-CN": '启用该端点'},
    "copy_b1719a8f3f": {"en": 'MCP', "zh-CN": 'MCP'},
    "copy_b1be526ebb": {"en": 'Unsupported skills action', "zh-CN": '不支持的技能操作'},
    "copy_b1d5dd1a0c": {"en": 'Action', "zh-CN": '操作'},
    "copy_b2f086be87": {"en": '{channel}: missing env `{name}`', "zh-CN": '{channel}: 缺少环境变量 `{name}`'},
    "copy_b334dbf724": {"en": 'tune budgets', "zh-CN": '调整预算'},
    "copy_b4405afe52": {"en": 'needs review if above zero', "zh-CN": '大于 0 需要处理'},
    "copy_b554959adb": {"en": 'credential storage', "zh-CN": '凭据存储方式'},
    "copy_b69f65c3f3": {"en": 'tools.enabled does not include `spawn`; background sub-agent capability is disabled.', "zh-CN": 'tools.enabled 未包含 `spawn`，后台子代理能力不可用。'},
    "copy_b8319fb312": {"en": 'Example: /data/lunaeclaw-exports or exports', "zh-CN": '例如：/data/lunaeclaw-exports 或 exports'},
    "copy_b9456b69aa": {"en": 'Import', "zh-CN": '导入'},
    "copy_b95244aab5": {"en": 'Config snippet (masked)', "zh-CN": '配置片段（脱敏）'},
    "copy_bb68b83d71": {"en": 'available', "zh-CN": '可用'},
    "copy_bc76551059": {"en": 'missing env: {hint}', "zh-CN": '缺少环境变量: {hint}'},
    "copy_bdd6a4e999": {"en": 'API Base', "zh-CN": 'API 地址'},
    "copy_bdeb1df337": {"en": 'Saved MCP server: {server_name}', "zh-CN": 'MCP 服务已保存: {server_name}'},
    "copy_be783d3e39": {"en": 'overwrite existing server', "zh-CN": '覆盖已有同名服务'},
    "copy_bf187784b8": {"en": 'Command (for stdio mode)', "zh-CN": '命令（stdio 模式）'},
    "copy_c13efabddc": {"en": 'GC interval in turns (gcEveryTurns, 0=off)', "zh-CN": 'GC 间隔轮次（gcEveryTurns，0=关闭）'},
    "copy_c258d63b0d": {"en": 'runtime and context pressure', "zh-CN": '运行时与上下文压力'},
    "copy_c2a837c0d5": {"en": 'Config', "zh-CN": '配置文件'},
    "copy_c7252673a1": {"en": 'plain text (not recommended)', "zh-CN": '明文（不推荐）'},
    "copy_c766efebde": {"en": 'Stdio command', "zh-CN": '标准输入输出命令'},
    "copy_c7af768dfc": {"en": 'manifest entry missing server_name', "zh-CN": 'manifest 条目缺少 server_name'},
    "copy_c80805754d": {"en": 'Budget alerts', "zh-CN": '预算告警'},
    "copy_ca3ec87f06": {"en": 'MCP Library', "zh-CN": 'MCP 库'},
    "copy_cae4ed6e49": {"en": 'missing command: {hint}', "zh-CN": '缺少命令: {hint}'},
    "copy_cb8da62408": {"en": 'failed to fetch skill URL: {error}', "zh-CN": '拉取 skill URL 失败: {error}'},
    "copy_cc9754586e": {"en": 'API Key', "zh-CN": 'API 密钥'},
    "copy_cdab38948a": {"en": 'Delete', "zh-CN": '删除'},
    "copy_ce386bcea5": {"en": 'skill_url must include host', "zh-CN": 'skill_url 必须包含主机名'},
    "copy_cf20d86a6c": {"en": 'invalid alias: {lhs} -> {rhs}', "zh-CN": 'alias 无效: {lhs} -> {rhs}'},
    "copy_cf3f4b45e3": {"en": 'Type', "zh-CN": '类型'},
    "copy_d0a0e99437": {"en": 'Skill name', "zh-CN": '技能名'},
    "copy_d0dcd15837": {"en": 'Skills config saved', "zh-CN": 'Skills 配置已保存'},
    "copy_d1a3716b38": {"en": 'Default Model', "zh-CN": '默认模型'},
    "copy_d23e378056": {"en": 'Please select a valid channel.', "zh-CN": '请选择一个有效渠道。'},
    "copy_d2e63e8b45": {"en": 'web_search provider is enabled, but web_search is not in tools.enabled.', "zh-CN": 'web_search provider 已启用，但 web_search 不在 tools.enabled。'},
    "copy_d33d99bb40": {"en": 'Disk', "zh-CN": '磁盘'},
    "copy_d58fe3eff7": {"en": 'MCP Servers', "zh-CN": 'MCP 服务'},
    "copy_d731db428a": {"en": 'Skills', "zh-CN": '技能'},
    "copy_d98c0f9a65": {"en": 'enable in skill selection', "zh-CN": '可在技能选择里启用'},
    "copy_d99390fcdd": {"en": 'In-chat quick switch commands', "zh-CN": '聊天内快捷切换命令'},
    "copy_d9e9a841af": {"en": 'history', "zh-CN": '历史上下文'},
    "copy_da159d15dc": {"en": 'MCP server not found: {name}', "zh-CN": 'MCP 服务不存在: {name}'},
    "copy_da94efacfc": {"en": 'requires: {hint}', "zh-CN": '依赖: {hint}'},
    "copy_dc4ca1d540": {"en": 'Args (CSV, stdio mode)', "zh-CN": '参数（CSV，stdio 模式）'},
    "copy_ddc9843ac5": {"en": 'Manage Channels', "zh-CN": '管理聊天渠道'},
    "copy_e05e1dba4e": {"en": 'Size', "zh-CN": '大小'},
    "copy_e0f2204417": {"en": 'Installed MCP from manifest: {server_name}', "zh-CN": '已从 manifest 安装 MCP: {server_name}'},
    "copy_e117e3ade1": {"en": 'web_search is set to exa_mcp, but exa MCP server is not configured.', "zh-CN": 'web_search 使用 exa_mcp，但未配置 exa MCP server。'},
    "copy_e1c753b2f4": {"en": 'Install', "zh-CN": '安装'},
    "copy_e1e78e6048": {"en": 'Runtime Paths & Counters', "zh-CN": '运行目录与计数'},
    "copy_e22992ebe6": {"en": 'Gateway auto-reload', "zh-CN": 'Gateway 自动热重载'},
    "copy_e2d32cb2de": {"en": 'FAIL', "zh-CN": '失败'},
    "copy_e539e84dae": {"en": 'Auto-compact background (structured first, truncate later)', "zh-CN": '自动压缩背景信息（优先结构化压缩，再截断）'},
    "copy_e53da62285": {"en": 'Disk used(/)', "zh-CN": '磁盘占用(/)'},
    "copy_e573c984a6": {"en": 'open endpoint and resave models', "zh-CN": '打开端点后重新保存 models'},
    "copy_e721609807": {"en": 'Unknown MCP library entry: {library_id}', "zh-CN": '未知 MCP 库条目: {library_id}'},
    "copy_e8f442342e": {"en": 'Install to Global', "zh-CN": '安装到全局'},
    "copy_e92d513a99": {"en": 'Manifest URL (raw JSON list)', "zh-CN": '清单 URL（raw JSON 列表）'},
    "copy_ea4be09f58": {"en": 'MCP server paused: {server_name}', "zh-CN": 'MCP 服务已暂停: {server_name}'},
    "copy_ea85f2b46c": {"en": 'No blocking issue found.', "zh-CN": '未发现阻塞问题。'},
    "copy_eb0935dd77": {"en": 'total context cap', "zh-CN": '总上下文预算'},
    "copy_eb1e822ae6": {"en": 'Description', "zh-CN": '说明'},
    "copy_ebb7c85be7": {"en": 'default_model cannot be empty.', "zh-CN": 'default_model 不能为空。'},
    "copy_ededde3efe": {"en": 'Server', "zh-CN": '服务'},
    "copy_ee97554ed4": {"en": 'Models (CSV)', "zh-CN": 'Models（逗号分隔）'},
    "copy_f234913c4f": {"en": 'Unknown skill library entry: {entry_id}', "zh-CN": '未知技能库条目: {entry_id}'},
    "copy_f3a178f5a1": {"en": 'media + exports total files', "zh-CN": 'media + exports 文件总数'},
    "copy_f433503b85": {"en": 'Path', "zh-CN": '路径'},
    "copy_f5e7ed533c": {"en": 'Name', "zh-CN": '名字'},
    "copy_f6287abbe3": {"en": 'allowFrom list (CSV)', "zh-CN": 'allowFrom 列表（逗号分隔）'},
    "copy_f6639efa56": {"en": 'id1, id2', "zh-CN": '用户ID1, 用户ID2'},
    "copy_f74fcb1799": {"en": 'Runtime & Context Budgets', "zh-CN": '资源与上下文预算'},
    "copy_f897aa302e": {"en": "MCP server '{name}' already exists. Enable overwrite to replace.", "zh-CN": "MCP 服务 '{name}' 已存在。勾选覆盖后可替换。"},
    "copy_f8edffc1b1": {"en": 'fix in Channels page', "zh-CN": '去渠道页面修复'},
    "copy_f99c379bf8": {"en": 'Missing endpoint name.', "zh-CN": '缺少端点名称。'},
    "copy_fc1314b439": {"en": 'Reset to default', "zh-CN": '恢复默认目录'},
    "copy_fc94e4673d": {"en": 'memory', "zh-CN": '记忆上下文'},
    "copy_fd1d8f61cd": {"en": 'URL (for HTTP mode)', "zh-CN": 'URL（HTTP 模式）'},
}
